name: 阅读z

on:
  workflow_dispatch:
  schedule:
     - cron: '0 1,10 * * *'
jobs:
  build:
    runs-on: ubuntu-latest    
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/tsuyoshi727/adr.git ~/adr
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          cd ~/adr
          npm install
          npm install cron
          npm install request
      - name: '运行 【中青阅读1】'
        run: |
          cd ~/adr
          node zqkd/zq_share.js
          node zqkd/zq_Rotary.js
          node zqkd/zq_friendSign.js
          node zqkd/zq_Adv_video.js
          node zqkd/zq_double.js
