# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 返利网

on:
    workflow_dispatch:
    schedule:
      - cron: "6 2,10,13 * * *"
    watch:
      types: [started]
    repository_dispatch:
      types: flw

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: '运行 【zqkkzddb】'
        run: |
          node zqyd/zq_share.js
          node zqyd/zq_Rotary.js
          node zqyd/zq_friendSign.js
          node zqyd/zq_Adv_video.js
          node zqyd/zq_double.js
        env:
          zq_cookie: ${{ secrets.zq_cookie }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
